Description: >
  Copyright; https://github.com/aws-samples/ecs-refarch-cloudformation/tree/master/infrastructure

  Template for Core components.

Parameters:
  EnvDBUsername:
    Description: ElephantSQL Database Username Enviroment Variable.
    Type: String

  EnvDBPassword:
    Description: ElephantSQL Database Password Enviroment Variable.
    Type: String

  EnvDBServer:
    Description: ElephantSQL Database Server Enviroment Variable.
    Type: String

  EnvDBName:
    Description: ElephantSQL Database Name Enviroment Variable.
    Type: String

  EnvDBPort:
    Description: ElephantSQL Database Port Enviroment Variable.
    Type: String

  EnvPort:
    Description: Server Port Enviroment Variable.
    Type: String
    Default: 8080

  EnvJWTSecret:
    Description: JWT Secret Enviroment Variable.
    Type: String

  EnvElephantSQLAPIKey:
    Description: ElephantSQL API Key Enviroment Variable.
    Type: String

  EnvAWSAccessKeyId:
    Description: AWS Access Key Id Enviroment Variable.
    Type: String

  EnvAWSSecretAccessKey:
    Description: AWS Secret Access Key Enviroment Variable.
    Type: String

  EnvCDNAWSAccessKeyId:
    Description: AWS CDN Access Key Id Enviroment Variable.
    Type: String

  EnvCDNAWSSecretAccessKey:
    Description: AWS CDN Secret Access Key Enviroment Variable.
    Type: String

Resources:
  SecretsCoreAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autshop.s3.eu-west-3.amazonaws.com/templates/secrets-manager/secrets-core-api.yaml
      Parameters:
        EnvDBUsername: !Ref EnvDBUsername
        EnvDBPassword: !Ref EnvDBPassword
        EnvDBServer: !Ref EnvDBServer
        EnvDBName: !Ref EnvDBName
        EnvDBPort: !Ref EnvDBPort
        EnvPort: !Ref EnvPort
        EnvJWTSecret: !Ref EnvJWTSecret
        EnvElephantSQLAPIKey: !Ref EnvElephantSQLAPIKey
        EnvAWSAccessKeyId: !Ref EnvAWSAccessKeyId
        EnvAWSSecretAccessKey: !Ref EnvAWSSecretAccessKey
        EnvCDNAWSAccessKeyId: !Ref EnvCDNAWSAccessKeyId
        EnvCDNAWSSecretAccessKey: !Ref EnvCDNAWSSecretAccessKey