Description: >
  Copyright; https://github.com/aws-samples/ecs-refarch-cloudformation/tree/master/infrastructure

  Template for Core components.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Description: Choose which VPC the Application Load Balancer should be deployed to
    Type: String

  PublicSubnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: String

  PrivateSubnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: String

  ECSHostSecurityGroup:
    Description: Select the Security Group to use for the ECS cluster hosts
    Type: AWS::EC2::SecurityGroup::Id

  LoadBalancerSecurityGroup:
    Description: Select the Security Group to apply to the Application Load Balancer
    Type: AWS::EC2::SecurityGroup::Id

  EnvAWSAccessKeyId:
    Description: AWS Access Key Id Enviroment Variable.
    Type: String

  EnvAWSSecretAccessKey:
    Description: AWS Secret Access Key Enviroment Variable.
    Type: String

  HostedZoneId:
    Description: Hosted Zone id.
    Type: String

Resources:
  S3BucketShopHome:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autshop.s3.eu-west-3.amazonaws.com/templates/s3/s3-bucket-shophome.yaml

  HostedZoneRecordShopHome:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autshop.s3.eu-west-3.amazonaws.com/templates/hosted-zone/hosted-zone-record-shophome.yaml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
    DependsOn: S3BucketShopHome