Description: >

  Copyright; https://github.com/aws-samples/ecs-refarch-cloudformation/tree/master/infrastructure

  Template for new Store.

Parameters:
  TenantName:
    Description: Slug name of tenant.
    Type: String

  HostedZoneId:
    Description: ID of hosted zone.
    Type: String

Resources:
  S3BucketShopCDN:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autshop.s3.eu-west-3.amazonaws.com/templates/s3/s3-bucket-shopcdn.yaml
      Parameters:
        TenantName: !Ref TenantName

  HostedZoneRecordShopCDN:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autshop.s3.eu-west-3.amazonaws.com/templates/hosted-zone/hosted-zone-record-shopcdn.yaml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        TenantName: !Ref TenantName
    DependsOn: S3BucketShopCDN

