Description: >

  Copyright; https://github.com/aws-samples/ecs-refarch-cloudformation/tree/master/infrastructure

  Template for new Store.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Description: Choose which VPC the Application Load Balancer should be deployed to
    Type: String

  PublicSubnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: String

  PrivateSubnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: String

  ECSHostSecurityGroup:
    Description: Select the Security Group to use for the ECS cluster hosts
    Type: AWS::EC2::SecurityGroup::Id

  LoadBalancerSecurityGroup:
    Description: Select the Security Group to apply to the Application Load Balancer
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/load-balancer-store-api.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPC: !Ref VPC
        Subnets: !Ref PublicSubnets
        SecurityGroup: !Ref LoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/ecs-cluster-store-api.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: t2.micro
        ClusterSize: 4
        VPC: !Ref VPC
        SecurityGroup: !Ref ECSHostSecurityGroup
        Subnets: !Ref PrivateSubnets


