Description: >

  Copyright; https://github.com/aws-samples/ecs-refarch-cloudformation/tree/master/infrastructure

  Template for new Store.

Parameters:
  VPC:
    Description: Choose which VPC the Application Load Balancer should be deployed to
    Type: String

  Cluster:
    Description: Please provide the ECS Cluster ID that this service should run on
    Type: String

  Listener:
    Description: The Application Load Balancer listener to register with
    Type: String

  TenantId:
    Description: Id of tenant.
    Type: Number

  TenantName:
    Description: Slug name of tenant.
    Type: String

  HostedZoneId:
    Description: ID of hosted zone.
    Type: String

  LoadBalancerDNS:
    Description: DNS of load balancer.
    Type: String

  Priority:
    Description: Priority of tenant.
    Type: Number
    Default: 1

Resources:
  ECSService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/ecs-service-store-api.yaml
      Parameters:
        VPC: !Ref VPC
        Cluster: !Ref Cluster
        DesiredCount: 2
        Listener: !Ref Listener
        TenantId: !Ref TenantId
        TenantName: !Ref TenantName

  RecordSet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/hosted-zone-record-store-api.yaml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        TenantId: !Ref TenantId
        TenantName: !Ref TenantName
        LoadBalancerDNS: !Ref LoadBalancerDNS
