Description: >

  Copyright; https://github.com/aws-samples/ecs-refarch-cloudformation/tree/master/infrastructure

  Template for new Store.

Parameters:
  VPC:
    Description: Choose which VPC the Application Load Balancer should be deployed to
    Type: String

  ClusterStoreAPI:
    Description: Please provide the ECS Cluster ID that this service should run on
    Type: String

  ClusterStorefront:
    Description: Please provide the ECS Cluster ID that this service should run on
    Type: String

  TenantId:
    Description: Id of tenant.
    Type: Number

  TenantName:
    Description: Slug name of tenant.
    Type: String

  HostedZoneId:
    Description: ID of hosted zone.
    Type: String

  LoadBalancerDNSStoreAPI:
    Description: DNS of load balancer.
    Type: String

  CanonicalHostedZoneIDStoreAPI:
    Description: The ID of the Amazon Route 53 hosted zone associated with the load balancer
    Type: String

  LoadBalancerDNSStorefront:
    Description: DNS of load balancer.
    Type: String

  CanonicalHostedZoneIDStorefront:
    Description: The ID of the Amazon Route 53 hosted zone associated with the load balancer
    Type: String

  ListenerStoreAPI:
    Description: The Application Load Balancer listener to register with
    Type: String

  ListenerStorefront:
    Description: The Application Load Balancer listener to register with
    Type: String

  Priority:
    Description: Priority of tenant.
    Type: Number
    Default: 1

Resources:
  ECSServiceStoreAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/service/ecs-service-store-api.yaml
      Parameters:
        VPC: !Ref VPC
        Cluster: !Ref ClusterStoreAPI
        DesiredCount: 2
        Listener: !Ref ListenerStoreAPI
        TenantId: !Ref TenantId
        TenantName: !Ref TenantName

  RecordSetStoreAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/hosted-zone/hosted-zone-record-store-api.yaml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        TenantId: !Ref TenantId
        TenantName: !Ref TenantName
        LoadBalancerDNS: !Ref LoadBalancerDNSStoreAPI
        CanonicalHostedZoneIDStoreAPI: !Ref CanonicalHostedZoneIDStoreAPI

  ECSServiceStorefront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/service/ecs-service-storefront.yaml
      Parameters:
        VPC: !Ref VPC
        Cluster: !Ref ClusterStorefront
        DesiredCount: 2
        Listener: !Ref ListenerStorefront
        TenantId: !Ref TenantId
        TenantName: !Ref TenantName

  RecordSetStorefront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://autstorebucket.s3.eu-west-3.amazonaws.com/templates/hosted-zone/hosted-zone-record-storefront.yaml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        TenantId: !Ref TenantId
        TenantName: !Ref TenantName
        LoadBalancerDNS: !Ref LoadBalancerDNSStorefront
        CanonicalHostedZoneIDStorefront: !Ref CanonicalHostedZoneIDStorefront

