Description: >
  Template for Shop Home website.

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "shop.akosfi.com"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref Bucket, /* ] ]