Description: >
  Secrets for core API.

Parameters:
  EnvAWSAccessKeyId:
    Description: AWS Access Key Id Enviroment Variable.
    Type: String

  EnvAWSSecretAccessKey:
    Description: AWS Secret Access Key Enviroment Variable.
    Type: String

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "core-api-secrets"
      SecretString: !Sub
        - '{"AWS_ACCESS_KEY_ID":"${AWS_ACCESS_KEY_ID}","AWS_SECRET_ACCESS_KEY":"${AWS_SECRET_ACCESS_KEY}"}'
        - AWS_ACCESS_KEY_ID: !Ref EnvAWSAccessKeyId
          AWS_SECRET_ACCESS_KEY: !Ref EnvAWSSecretAccessKey

Outputs:
  SecretArn:
    Value: !Ref Secret