Description: >
  Secrets for store API.

Parameters:
  TenantId:
    Description: Id of tenant.
    Type: Number

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join [ "-", [ "tenant", "secrets", !Ref TenantId ] ]
      SecretString: '{"DB_USERNAME":"MasterUsername","DB_PASSWORD":"secret-password", "DB_SERVER":"db-server", "DB_NAME": "db_name", "DB_PORT": "db-port"}'