Description: >
  Secrets for Store.

Parameters:
  TenantId:
    Description: Id of tenant.
    Type: Number

  EnvDbUsername:
    Description: DB Username Enviroment Variable.
    Type: String

  EnvDbPassword:
    Description: DB Password Enviroment Variable.
    Type: String

  EnvDbServer:
    Description: DB Server Enviroment Variable.
    Type: String

  EnvDbName:
    Description: DB Name Enviroment Variable.
    Type: String

  EnvDbPort:
    Description: DB Port Enviroment Variable.
    Type: String

  EnvServerURL:
    Description: Server URL Enviroment Variable.
    Type: String

  EnvTenantName:
    Description: Tenant Name Enviroment Variable.
    Type: String

  EnvCDNAWSAccessKeyId:
    Description: AWS CDN Access Key Id Enviroment Variable.
    Type: String

  EnvCDNAWSSecretAccessKey:
    Description: AWS CDN Secret Access Key Enviroment Variable.
    Type: String

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join [ "-", [ "tenant", "secrets", !Ref TenantId ] ]
      SecretString: !Sub
        - '{"DB_USERNAME":"${DB_USERNAME}","DB_PASSWORD":"${DB_PASSWORD}", "DB_SERVER":"${DB_SERVER}", "DB_NAME": "${DB_NAME}", "DB_PORT": "${DB_PORT}", "NEXT_PUBLIC_SERVER_URL": "${NEXT_PUBLIC_SERVER_URL}", "NEXT_PUBLIC_TENANT_NAME": "${NEXT_PUBLIC_TENANT_NAME}", "AWS_CDN_ACCESS_KEY_ID": "${AWS_CDN_ACCESS_KEY_ID}", "AWS_CDN_SECRET_ACCESS_KEY": "${AWS_CDN_SECRET_ACCESS_KEY}", "CORE_API_URL": "${CORE_API_URL}"}'
        - DB_USERNAME: !Ref EnvDbUsername
          DB_PASSWORD: !Ref EnvDbPassword
          DB_SERVER: !Ref EnvDbServer
          DB_NAME: !Ref EnvDbName
          DB_PORT: !Ref EnvDbPort
          NEXT_PUBLIC_SERVER_URL: !Ref EnvServerURL
          NEXT_PUBLIC_TENANT_NAME: !Ref EnvTenantName
          AWS_CDN_ACCESS_KEY_ID: !Ref EnvCDNAWSAccessKeyId
          AWS_CDN_SECRET_ACCESS_KEY: !Ref EnvCDNAWSSecretAccessKey
          CORE_API_URL: "http://api.shop.akosfi.com"

Outputs:
  SecretArn:
    Value: !Ref Secret