Description: >
  Secrets for store API.

Parameters:
  TenantId:
    Description: Id of tenant.
    Type: Number

  ENV_DB_USERNAME:
    Description: DB Username Enviroment Variable.
    Type: String

  ENV_DB_PASSWORD:
    Description: DB Password Enviroment Variable.
    Type: String

  ENV_DB_SERVER:
    Description: DB Server Enviroment Variable.
    Type: String

  ENV_DB_NAME:
    Description: DB Name Enviroment Variable.
    Type: String

  ENV_DB_PORT:
    Description: DB Port Enviroment Variable.
    Type: String

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join [ "-", [ "tenant", "secrets", !Ref TenantId ] ]
      SecretString: !Sub
        - '{"DB_USERNAME":"${DB_USERNAME}","DB_PASSWORD":"${DB_PASSWORD}", "DB_SERVER":"${DB_SERVER}", "DB_NAME": "${DB_NAME}", "DB_PORT": "${DB_PORT}"}'
        - DB_USERNAME: !Ref DB_USERNAME
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_SERVER: !Ref DB_SERVER
          DB_NAME: !Ref DB_NAME
          DB_PORT: !Ref DB_PORT

Outputs:
  SecretArn:
    Value: !Ref Secret