Description: >
  Shop cdn hosted zone template.

Parameters:
  HostedZoneId:
    Description: Id of hosted zone.
    Type: String

  TenantName:
    Description: Name of Tenant.
    Type: String

Resources:
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub
        - "cdn.${TenantName}.shop.akosfi.com"
        - { TenantName: !Ref TenantName }
      AliasTarget:
        #https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints
        HostedZoneId: "Z3R1K369G5AVDG"
        DNSName: "s3-website.eu-west-3.amazonaws.com"
        EvaluateTargetHealth: false
      Type: A