Description: >
  Codebuild project template for Shop Admin.

Parameters:
  GithubAccessToken:
    Description: Github Personal Access Token.
    Type: String

Resources:
  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: !Ref GithubAccessToken