Description: >
  Codebuild project template for Shop Admin.

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codebuild-shop-storeadmin-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: shop-storeadmin
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0-21.04.23
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: TENANT_ID
            Value: 1
      Source:
        Type: GITHUB
        Location: https://github.com/autshop/storeadmin.git
        Auth:
          Resource: NO_NEED_TO_SPECIFY_THIS_ACCORDING_TO_DOCS
          Type: OAUTH
      Triggers:
        FilterGroups:
          - - Pattern: PUSH
              Type: EVENT
        Webhook: true
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 10
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
