Description: >
  ECS task execution role.

Parameters:
  TenantId:
    Description: Id of tenant.
    Type: Number

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [ "ecsTaskExecutionRole", "tenant", !Ref TenantId ] ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: AccessSecretsManager
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
